Repository boostcampwm-2024/iOS07-alsongDalsong, pull requests merged in 2024-11, with the labels that each got.

#6 chore: 주석 및 필요없는 코드 제거
  alsongDalsong/AppDelegate.swift
  alsongDalsong/SceneDelegate.swift
  alsongDalsong/ViewController.swift
Labels: chore

#7 test: PR 머지 테스트
  .github/workflows/merge-to-main.yml
  alsongDalsong/Assets.xcassets/fake.imageset/Contents.json
  alsongDalsong/Assets.xcassets/fake.imageset/fake.png
  alsongDalsong/ViewController.swift
Labels: test

#8 test: PR Merge 연습
  alsongDalsong/ViewController.swift
Labels: test

#9 test: PR merge 연습
  alsongDalsong/Assets.xcassets/fake.imageset/Contents.json
  alsongDalsong/Assets.xcassets/fake.imageset/fake.png
  alsongDalsong/Assets.xcassets/fake.imageset/fake@2x.png
  alsongDalsong/Assets.xcassets/fake.imageset/fake@3x.png
  alsongDalsong/ViewController.swift
Labels: test

#21 chore: Color Asset, Font 추가
  alsongDalsong/Assets.xcassets/asGreen.colorset/Contents.json
  alsongDalsong/Assets.xcassets/asLightGray.colorset/Contents.json
  alsongDalsong/Assets.xcassets/asLightRed.colorset/Contents.json
  alsongDalsong/Assets.xcassets/asLightSky.colorset/Contents.json
  alsongDalsong/Assets.xcassets/asMint.colorset/Contents.json
  alsongDalsong/Assets.xcassets/asShadow.colorset/Contents.json
  alsongDalsong/Assets.xcassets/asYellow.colorset/Contents.json
  alsongDalsong/Extensions/UIFont+.swift
  alsongDalsong/Fonts/DoHyeon-Regular.ttf
  alsongDalsong/Info.plist
Labels: chore

#16 feat: 녹음 기능 구현
  ASAudioKit.xcodeproj/project.pbxproj
  ASAudioKit.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ASAudioKit/ASAudioKit.docc/ASAudioKit.md
  ASAudioKit/ASAudioKit.h
  ASAudioKit/ASAudioPlayer/ASAudioPlayer.swift
  ASAudioKit/ASAudioRecorder/ASAudioRecorder.swift
  ASAudioKitTests/ASAudioRecorderTests.swift
  alsongDalsong.xcodeproj/project.pbxproj
Labels: feat, chore

#23 feat: 재생 기능 구현
  ASAudioKit.xcodeproj/project.pbxproj
  ASAudioKit/ASAudioPlayer/ASAudioPlayer.swift
  ASAudioKit/ASAudioPlayer/README.md
  ASAudioKit/ASAudioRecorder/ASAudioRecorder.swift
  ASAudioKitTests/ASAudioPlayerTests.swift
  ASAudioKitTests/TestData/PlayTestDrum.wav
Labels: feat

#35 chore: SwiftLint 적용
  .swiftlint.yml
  ASAudioKit.xcodeproj/project.pbxproj
  ASAudioKit/ASAudioPlayer/ASAudioPlayer.swift
  ASAudioKit/ASAudioRecorder/ASAudioRecorder.swift
  ASAudioKitTests/ASAudioPlayerTests.swift
  ASAudioKitTests/ASAudioRecorderTests.swift
  alsongDalsong.xcodeproj/project.pbxproj
  alsongDalsong/SceneDelegate.swift
  alsongDalsong/ViewController.swift
Labels: chore

#33 feat: Firebase Function 구조 설계 및 방 생성, 방 참가, 게임 시작, 허밍모드 룰 설정
  firebase/.firebaserc
  firebase/firebase.json
  firebase/functions/.gitignore
  firebase/functions/FirebaseAdmin.js
  firebase/functions/api/CreateRoom.js
  firebase/functions/api/GetRecord.js
  firebase/functions/api/GetResult.js
  firebase/functions/api/GetUserAvatar.js
  firebase/functions/api/JoinRoom.js
  firebase/functions/api/ResetGame.js
  firebase/functions/api/SetAnswer.js
  firebase/functions/api/StartGame.js
  firebase/functions/api/SubmitAnswer.js
  firebase/functions/api/UploadRecord.js
  firebase/functions/common/GameHelper.js
  firebase/functions/common/RoomHelper.js
  firebase/functions/index.js
  firebase/functions/package-lock.json
  firebase/functions/package.json
  firebase/functions/trigger/onRecordAdded.js
Labels: feat

#29 feat: entity 모듈 구현 및 추가
  ASEntity.xcodeproj/project.pbxproj
  ASEntity.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ASEntity/Answer.swift
  ASEntity/Mode.swift
  ASEntity/Music.swift
  ASEntity/Player.swift
  ASEntity/Playlist.swift
  ASEntity/Record.swift
  ASEntity/Room.swift
  ASEntity/Status.swift
  alsongDalsong.xcodeproj/project.pbxproj
  alsongDalsong/Components/RecordButton.swift
Labels: feat

#41 feat: 말풍선 셀 구현
  alsongDalsong/Components/AvatarCircle.swift
  alsongDalsong/Components/SpeechBubbleCell.swift
Labels: feat

#39 feat: ASButton 구현
  alsongDalsong.xcodeproj/project.pbxproj
  alsongDalsong/Components/UIKitComponents/ASButton.swift
  alsongDalsong/Extensions/UIView+.swift
Labels: feat

#27 feat: 캐싱 모듈 구현
  ASAudioKit.xcodeproj/xcshareddata/xcschemes/ASAudioKit.xcscheme
  ASCacheKit.xcodeproj/project.pbxproj
  ASCacheKit.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ASCacheKit.xcodeproj/xcshareddata/xcschemes/ASCacheKit.xcscheme
  ASCacheKit.xcodeproj/xcshareddata/xcschemes/ASCacheKitTests.xcscheme
  ASCacheKit/Core/Extension/String+Encrypt.swift
  ASCacheKit/Core/Source/ASCacheManager.swift
  ASCacheKit/Core/Source/CacheOption.swift
  ASCacheKit/Core/Source/DiskCache.swift
  ASCacheKit/Core/Source/MemoryCache.swift
  ASCacheKit/Protocol/DiskCacheManagerProtocol.swift
  ASCacheKit/Protocol/MemoryCacheManagerProtocol.swift
  ASCacheKit/Protocol/URLSessionProtocol.swift
  ASCacheKitTests/ASCacheKitTests.swift
  ASCacheKitTests/Mock/MockDiskCacheManager.swift
  ASCacheKitTests/Mock/MockMemoryCacheManager.swift
  ASCacheKitTests/Mock/MockURLSession.swift
  alsongDalsong.xcodeproj/project.pbxproj
Labels: feat

#43 feat: 랜덤 닉네임 생성기 구현
  alsongDalsong/Util/NickNameGenerator.swift
Labels: feat

#48 feat: ASEncoder, ASDecoder 모듈 구현
  ASDecoder.xcodeproj/project.pbxproj
  ASDecoder.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ASDecoder.xcodeproj/xcshareddata/xcschemes/ASDecoder.xcscheme
  ASDecoder.xcodeproj/xcshareddata/xcschemes/ASDecoderTests.xcscheme
  ASDecoder/ASDecoder.swift
  ASDecoderTests/ASDecoderTests.swift
  ASEncoder.xcodeproj/project.pbxproj
  ASEncoder.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ASEncoder.xcodeproj/xcshareddata/xcschemes/ASEncoder.xcscheme
  ASEncoder.xcodeproj/xcshareddata/xcschemes/ASEncoderTests.xcscheme
  ASEncoder/ASEncoder.swift
  ASEncoderTests/ASEncoderTests.swift
  alsongDalsong.xcodeproj/project.pbxproj
Labels: feat

#38 chore: 파이어베이스 SPM 설치 및 세팅
  .gitignore
  alsongDalsong.xcodeproj/project.pbxproj
  alsongDalsong.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  alsongDalsong.xcodeproj/xcshareddata/xcschemes/alsongDalsong.xcscheme
  alsongDalsong/SceneDelegate.swift
Labels: chore

#47 feat: ASTextField, ASPanel, 메인화면 UI (부분완)
  alsongDalsong.xcodeproj/project.pbxproj
  alsongDalsong/Assets.xcassets/logo.imageset/Contents.json
  alsongDalsong/Assets.xcassets/logo.imageset/알쏭달쏭로고.png
  alsongDalsong/Assets.xcassets/mojojojo.imageset/Contents.json
  alsongDalsong/Assets.xcassets/mojojojo.imageset/mojojojo.png
  alsongDalsong/Components/UIKitComponents/ASAvatarCircleView.swift
  alsongDalsong/Components/UIKitComponents/ASPanel.swift
  alsongDalsong/Components/UIKitComponents/ASRefreshButton.swift
  alsongDalsong/Components/UIKitComponents/ASTextField.swift
  alsongDalsong/ViewController.swift
Labels: feat

#45 feat: 네트워크 모듈 구현
  ASNetworkKit.xcodeproj/project.pbxproj
  ASNetworkKit.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ASNetworkKit/ASNetworkErrors.swift
  ASNetworkKit/ASNetworkManager.swift
  ASNetworkKit/Endpoint.swift
  ASNetworkKit/FirebaseEndpoint.swift
  ASNetworkKit/HTTPMethod.swift
  ASNetworkKit/Protocols/URLSessionProtocol.swift
  ASNetworkKit/RequestBuilder.swift
  ASNetworkKitTests/ASNetworkKitTests.swift
  ASNetworkKitTests/MockURLSession.swift
  alsongDalsong.xcodeproj/project.pbxproj
Labels: feat

#62 feat: 파이어베이스 데모, 방생성/방참가 기능 구현
  .gitignore
  alsongDalsong/ASEntity/ASEntity/Answer.swift
  alsongDalsong/ASEntity/ASEntity/Music.swift
  alsongDalsong/ASEntity/ASEntity/Player.swift
  alsongDalsong/ASEntity/ASEntity/Playlist.swift
  alsongDalsong/ASEntity/ASEntity/Record.swift
  alsongDalsong/ASEntity/ASEntity/Room.swift
  alsongDalsong/ASEntity/ASEntity/Status.swift
  alsongDalsong/ASNetworkKit/ASFirebaseDemo/Resources/Info.plist
  alsongDalsong/ASNetworkKit/ASFirebaseDemo/Sources/AppDelegate.swift
  alsongDalsong/ASNetworkKit/ASFirebaseDemo/Sources/Base.lproj/LaunchScreen.storyboard
  alsongDalsong/ASNetworkKit/ASFirebaseDemo/Sources/Lobby/LobbyViewController.swift
  alsongDalsong/ASNetworkKit/ASFirebaseDemo/Sources/Lobby/LobbyViewModel.swift
  alsongDalsong/ASNetworkKit/ASFirebaseDemo/Sources/Main/MainViewController.swift
  alsongDalsong/ASNetworkKit/ASFirebaseDemo/Sources/SceneDelegate.swift
  alsongDalsong/ASNetworkKit/ASNetworkKit.xcodeproj/project.pbxproj
  alsongDalsong/ASNetworkKit/ASNetworkKit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  alsongDalsong/ASNetworkKit/ASNetworkKit/ASNetworkErrors.swift
  alsongDalsong/ASNetworkKit/ASNetworkKit/ASNetworkManager.swift
  alsongDalsong/ASNetworkKit/ASNetworkKit/Endpoint.swift
  alsongDalsong/ASNetworkKit/ASNetworkKit/Firebase/ASFirebaseAuthProtocol.swift
  alsongDalsong/ASNetworkKit/ASNetworkKit/Firebase/ASFirebaseDatabaseProtocol.swift
  alsongDalsong/ASNetworkKit/ASNetworkKit/Firebase/ASFirebaseManager.swift
  alsongDalsong/ASNetworkKit/ASNetworkKit/FirebaseEndpoint.swift
  alsongDalsong/alsongDalsong/alsongDalsong.xcodeproj/project.pbxproj
  firebase/functions/api/CreateRoom.js
  firebase/functions/api/GetRecord.js
  firebase/functions/api/GetResult.js
  firebase/functions/api/JoinRoom.js
  firebase/functions/api/StartGame.js
  firebase/functions/trigger/onRecordAdded.js
Labels: feat

#56 feat: 인코딩/디코딩 모듈 데모 앱 구현
  alsongDalsong/ASDecoder/ASDecoder.xcodeproj/project.pbxproj
  alsongDalsong/ASDecoder/ASDecoderDemo/ASDecoderDemoApp.swift
  alsongDalsong/ASDecoder/ASDecoderDemo/ASDecoderDemoView.swift
  alsongDalsong/ASDecoder/ASDecoderDemo/ASDecoderDemoViewModel.swift
  alsongDalsong/ASDecoder/ASDecoderDemo/Assets.xcassets/AccentColor.colorset/Contents.json
  alsongDalsong/ASDecoder/ASDecoderDemo/Assets.xcassets/AppIcon.appiconset/Contents.json
  alsongDalsong/ASDecoder/ASDecoderDemo/Assets.xcassets/Contents.json
  alsongDalsong/ASDecoder/ASDecoderDemo/DemoModels.swift
  alsongDalsong/ASDecoder/ASDecoderDemo/JSONDataScenarios.swift
  alsongDalsong/ASDecoder/ASDecoderDemo/Preview Content/Preview Assets.xcassets/Contents.json
  alsongDalsong/ASDecoder/ASDecoderDemo/ViewModifiers.swift
  alsongDalsong/ASEncoder/ASEncoder.xcodeproj/project.pbxproj
  alsongDalsong/ASEncoder/ASEncoderDemo/ASEncoderDemoApp.swift
  alsongDalsong/ASEncoder/ASEncoderDemo/Assets.xcassets/AccentColor.colorset/Contents.json
  alsongDalsong/ASEncoder/ASEncoderDemo/Assets.xcassets/AppIcon.appiconset/Contents.json
  alsongDalsong/ASEncoder/ASEncoderDemo/Assets.xcassets/Contents.json
  alsongDalsong/ASEncoder/ASEncoderDemo/DemoModels.swift
  alsongDalsong/ASEncoder/ASEncoderDemo/EncodingDemoView.swift
  alsongDalsong/ASEncoder/ASEncoderDemo/EncodingDemoViewModel.swift
  alsongDalsong/ASEncoder/ASEncoderDemo/Preview Content/Preview Assets.xcassets/Contents.json
  alsongDalsong/ASNetworkKit/ASNetworkKit.xcodeproj/project.pbxproj
Labels: feat

#58 feat: 캐싱 모듈 데모 앱 구현
  alsongDalsong/ASCacheKit/ASCacheKit.xcodeproj/project.pbxproj
  alsongDalsong/ASCacheKit/ASCacheKitDemo/ASCacheKitDemoApp.swift
  alsongDalsong/ASCacheKit/ASCacheKitDemo/ASCacheKitDemoView.swift
  alsongDalsong/ASCacheKit/ASCacheKitDemo/ASCacheKitDemoViewModel.swift
  alsongDalsong/ASCacheKit/ASCacheKitDemo/Assets.xcassets/AccentColor.colorset/Contents.json
  alsongDalsong/ASCacheKit/ASCacheKitDemo/Assets.xcassets/AppIcon.appiconset/Contents.json
  alsongDalsong/ASCacheKit/ASCacheKitDemo/Assets.xcassets/Contents.json
  alsongDalsong/ASCacheKit/ASCacheKitDemo/Preview Content/Preview Assets.xcassets/Contents.json
  alsongDalsong/ASCacheKit/ASCacheKitDemo/Toast.swift
Labels: feat

#61 feat: ASAudioKit 데모앱 구현
  alsongDalsong/ASAudioKit/ASAudioDemo/ASAudioDemoApp.swift
  alsongDalsong/ASAudioKit/ASAudioDemo/ASAudioKitDemoView.swift
  alsongDalsong/ASAudioKit/ASAudioDemo/ASAudioKitDemoViewModel.swift
  alsongDalsong/ASAudioKit/ASAudioDemo/Assets.xcassets/AccentColor.colorset/Contents.json
  alsongDalsong/ASAudioKit/ASAudioDemo/Assets.xcassets/AppIcon.appiconset/Contents.json
  alsongDalsong/ASAudioKit/ASAudioDemo/Assets.xcassets/Contents.json
  alsongDalsong/ASAudioKit/ASAudioDemo/AudioVisualizerView.swift
  alsongDalsong/ASAudioKit/ASAudioDemo/Preview Content/Preview Assets.xcassets/Contents.json
  alsongDalsong/ASAudioKit/ASAudioKit.xcodeproj/project.pbxproj
  alsongDalsong/ASAudioKit/ASAudioKit/ASAudioPlayer/ASAudioPlayer.swift
  alsongDalsong/ASAudioKit/ASAudioKit/ASAudioRecorder/ASAudioRecorder.swift
Labels: feat

#65 Feat: 네트워크 모듈에 캐싱 추가
  alsongDalsong/ASCacheKit/ASCacheKit.xcodeproj/project.pbxproj
  alsongDalsong/ASCacheKit/ASCacheKit/Core/Source/ASCacheManager.swift
  alsongDalsong/ASCacheKit/ASCacheKit/Core/Source/DiskCache.swift
  alsongDalsong/ASCacheKit/ASCacheKit/Core/Source/MemoryCache.swift
  alsongDalsong/ASCacheKit/ASCacheKit/Protocol/URLSessionProtocol.swift
  alsongDalsong/ASCacheKit/ASCacheKitDemo/ASCacheKitDemoViewModel.swift
  alsongDalsong/ASCacheKit/ASCacheKitProtocol/CacheManagerProtocol.swift
  alsongDalsong/ASCacheKit/ASCacheKitProtocol/CacheOption.swift
  alsongDalsong/ASCacheKit/ASCacheKitProtocol/DiskCacheManagerProtocol.swift
  alsongDalsong/ASCacheKit/ASCacheKitProtocol/MemoryCacheManagerProtocol.swift
  alsongDalsong/ASCacheKit/ASCacheKitTests/ASCacheKitTests.swift
  alsongDalsong/ASCacheKit/ASCacheKitTests/Mock/MockDiskCacheManager.swift
  alsongDalsong/ASCacheKit/ASCacheKitTests/Mock/MockMemoryCacheManager.swift
  alsongDalsong/ASCacheKit/ASCacheKitTests/Mock/MockURLSession.swift
  alsongDalsong/ASNetworkKit/ASNetworkKit.xcodeproj/project.pbxproj
  alsongDalsong/ASNetworkKit/ASNetworkKit.xcodeproj/xcshareddata/xcschemes/ASNetworkKit.xcscheme
  alsongDalsong/ASNetworkKit/ASNetworkKit/ASNetworkManager.swift
Labels: feat

#69 feat: Main Repository 구현
  alsongDalsong.xcworkspace/contents.xcworkspacedata
  alsongDalsong/ASEntity/ASEntity/Answer.swift
  alsongDalsong/ASEntity/ASEntity/Music.swift
  alsongDalsong/ASEntity/ASEntity/Player.swift
  alsongDalsong/ASEntity/ASEntity/Playlist.swift
  alsongDalsong/ASEntity/ASEntity/Record.swift
  alsongDalsong/ASNetworkKit/ASNetworkKit.xcodeproj/project.pbxproj
  alsongDalsong/ASNetworkKit/ASNetworkKit/Firebase/ASFirebaseDatabaseProtocol.swift
  alsongDalsong/ASNetworkKit/ASNetworkKit/Firebase/ASFirebaseManager.swift
  alsongDalsong/ASRepository/ASRepository.xcodeproj/project.pbxproj
  alsongDalsong/ASRepository/ASRepository/Protocols/MainRepositoryProtocol.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/MainRepository.swift
  alsongDalsong/ASRepository/ASRepository/Wrappers/PublishedValue.swift
Labels: feat

#74 feat: 오디오 비주얼라이저 UI 구현
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/AudioVisualizerView.swift
Labels: feat

#76 Feat: HummingView와 속한 컴포넌트 구현
  alsongDalsong/ASRepository/ASRepository/Repositories/GameStatusRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/PlayersRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/SubmitsRepository.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ASButton.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/GuideLabel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ProgressBar.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/SubmissionStatusView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Extensions/UIFont+.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Humming/HummingView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Humming/HummingViewModel.swift
Labels: feat

#80 refactor: Reopsitory 타입을 구조체 -> 클래스로 변경
  alsongDalsong/ASRepository/ASRepository/Repositories/AnswersRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/GameStatusRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/MainRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/PlayersRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/RecordsRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/RoomInfoRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/SelectedRecordsRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/SubmitsRepository.swift
Labels: refactor

#83 feat: 녹음 파일 업로드 (CF)
  firebase/functions/api/UploadRecord.js
Labels: feat

#90 feat: 허밍모드 결과 UI 구현
  alsongDalsong/ASEntity/ASEntity/Music.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/AvatarCircle.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/SpeechBubbleCell.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ASAvatarCircleView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ASButton.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/AudioVisualizerView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Result/HummingResultViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Result/HummingResultViewModel.swift
Labels: feat

#98 feat: 내 UID 가져오는 기능
  alsongDalsong/ASNetworkKit/ASNetworkKit/Firebase/ASFirebaseAuth.swift
  alsongDalsong/ASNetworkKit/ASNetworkKit/Protocols/ASFirebaseAuthProtocol.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/RoomActionRepository.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/SceneDelegate.swift
Labels: feat

#99 feat: 온보딩 UI 수정
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ASAlertController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ASButton.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ASTextField.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Extensions/UIViewController+Keyboard.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Onboarding/OnboardingViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Onboarding/OnboardingViewModel.swift
Labels: feat

#96 QA: 로비 UI 수정
  alsongDalsong/ASEntity/ASEntity/Mode.swift
  alsongDalsong/ASNetworkKit/ASNetworkKit/Firebase/ASFirebaseDatabase.swift
  alsongDalsong/ASNetworkKit/ASNetworkKit/FirebaseEndpoint.swift
  alsongDalsong/ASNetworkKit/ASNetworkKit/Protocols/ASFirebaseDatabaseProtocol.swift
  alsongDalsong/ASRepository/ASRepository/Protocols/MainRepositoryProtocol.swift
  alsongDalsong/ASRepository/ASRepository/Protocols/RepositoryProtocols.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/MainRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/PlayersRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/RoomActionRepository.swift
  alsongDalsong/ASRepository/ASRepository/RepsotioryAssembly.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Localizable.xcstrings
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/SwiftUIComponents/ModeView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/SwiftUIComponents/SnapperView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ASAlertController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Extensions/UIImage+Flip.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Extensions/UIViewController+Keyboard.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/SceneDelegate.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Lobby/LobbyView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Lobby/LobbyViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Lobby/LobbyViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Onboarding/OnboardingViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Onboarding/OnboardingViewModel.swift
  firebase/functions/api/ChangeMode.js
  firebase/functions/api/ExitRoom.js
  firebase/functions/api/StartGame.js
  firebase/functions/index.js
  firebase/functions/package-lock.json
  firebase/functions/package.json
  firebase/functions/trigger/onRemovePlayer.js
Labels: feat, QA

#102 fix: 버그 수정
  alsongDalsong/alsongDalsong/alsongDalsong/Resources/Assets.xcassets/asOrange.colorset/Contents.json
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ASAlertController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ASPanel.swift
Labels: fix

#105 feat: 허밍/리허밍 뷰 완성
  alsongDalsong/ASAudioKit/ASAudioKit/ASAudioPlayer/ASAudioPlayer.swift
  alsongDalsong/ASEntity/ASEntity/Music.swift
  alsongDalsong/ASEntity/ASEntity/Record.swift
  alsongDalsong/ASEntity/ASEntity/Room.swift
  alsongDalsong/ASRepository/ASRepository/Protocols/MainRepositoryProtocol.swift
  alsongDalsong/ASRepository/ASRepository/Protocols/RepositoryProtocols.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/GameStatusRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/MainRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/RecordsRepository.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ASButton.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Utils/AudioHelper.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Humming/HummingView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Humming/HummingViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/RecordingPanel/PanelState.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/RecordingPanel/RecordingPanel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/RecordingPanel/RecordingPanelViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Rehumming/RehummingView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Rehumming/RehummingViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SelectMusic/SelectMusicViewController.swift
Labels: feat

#104 feat: 결과 화면 UI 수정 및 흐름 구현
  alsongDalsong/ASEntity/ASEntity/Answer.swift
  alsongDalsong/ASEntity/ASEntity/Music.swift
  alsongDalsong/ASEntity/ASEntity/Player.swift
  alsongDalsong/ASEntity/ASEntity/Record.swift
  alsongDalsong/ASRepository/ASRepository/Protocols/RepositoryProtocols.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/HummingResultRepository.swift
  alsongDalsong/ASRepository/ASRepository/RepsotioryAssembly.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Resources/SampleRecord.m4a
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/SpeechBubbleCell.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Onboarding/OnboardingViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Rehumming/RehummingView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Result/HummingResultViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Result/HummingResultViewModel.swift
Labels: feat, QA

#108 feat: Progress UI 구현
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ASAlertController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ASAvatarCircleView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ASButton.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ASPanel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ASTextField.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/NicknamePanel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Extensions/UIViewController+present.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Lobby/LobbyViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Onboarding/OnboardingViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Onboarding/OnboardingViewModel.swift
Labels: feat

#113 feat: firebase dueTime 제어, ASRepository dueTime 값 디코딩이 안되던 문제 해결
  firebase/functions/api/StartGame.js
  firebase/functions/api/SubmitMusic.js
  firebase/functions/api/UploadRecord.js
  firebase/functions/common/RoomHelper.js
  firebase/functions/index.js
  firebase/functions/trigger/onRecordAdded.js
Labels: feat, fix

#120 feat: 결과 화면 UI 흐름 구현 및 RecordOrder CF 구현
  alsongDalsong/ASEntity/ASEntity/Record.swift
  alsongDalsong/ASNetworkKit/ASNetworkKit/FirebaseEndpoint.swift
  alsongDalsong/ASRepository/ASRepository/Protocols/RepositoryProtocols.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/HummingResultRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/RoomActionRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/RoomInfoRepository.swift
  alsongDalsong/ASRepository/ASRepository/RepsotioryAssembly.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/SceneDelegate.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Humming/HummingViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Result/HummingResultViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Result/HummingResultViewModel.swift
  firebase/functions/api/ChangeRecordOrder.js
  firebase/functions/index.js
Labels: feat

#119 feat: 정답 제출 UI + API 구현
  alsongDalsong/ASNetworkKit/ASNetworkKit/FirebaseEndpoint.swift
  alsongDalsong/ASRepository/ASRepository/Protocols/RepositoryProtocols.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/SubmitsRepository.swift
  alsongDalsong/ASRepository/ASRepository/RepsotioryAssembly.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Localizable.xcstrings
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SubmitAnswer/SelectAnswerView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SubmitAnswer/SubmitAnswerViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SubmitAnswer/SubmitAnswerViewModel.swift
  firebase/functions/api/SubmitAnswer.js
Labels: feat

#111 feat: 허밍모드 Status에 따른 Navigation 구현
  alsongDalsong/ASEntity/ASEntity/GameState.swift
  alsongDalsong/ASEntity/ASEntity/Record.swift
  alsongDalsong/ASEntity/ASEntity/Room.swift
  alsongDalsong/ASRepository/ASRepository/Protocols/RepositoryProtocols.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/AnswersRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/GameStateRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/GameStatusRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/HummingResultRepository.swift
  alsongDalsong/ASRepository/ASRepository/RepsotioryAssembly.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/SceneDelegate.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Game/GameNavigationController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Humming/HummingViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Lobby/LobbyViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Onboarding/OnboardingViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SelectMusic/SelectMusicViewController.swift
  firebase/functions/api/StartGame.js
  firebase/functions/api/UploadRecord.js
  firebase/functions/common/RoomHelper.js
  firebase/functions/trigger/onRecordAdded.js
Labels: feat

#124 feat: 녹음 파일 전송 기능 구현
  alsongDalsong/ASNetworkKit/ASFirebaseDemo/Sources/Lobby/LobbyViewModel.swift
  alsongDalsong/ASNetworkKit/ASNetworkKit/ASNetworkManager.swift
  alsongDalsong/ASNetworkKit/ASNetworkKit/FirebaseEndpoint.swift
  alsongDalsong/ASNetworkKit/ASNetworkKit/HTTPContentType.swift
  alsongDalsong/ASNetworkKit/ASNetworkKit/Protocols/ASNetworkManagerProtocol.swift
  alsongDalsong/ASRepository/ASRepository/Protocols/MainRepositoryProtocol.swift
  alsongDalsong/ASRepository/ASRepository/Protocols/RepositoryProtocols.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/AnswersRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/AvatarRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/MainRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/MusicRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/PlayersRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/RecordsRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/RoomActionRepository.swift
  alsongDalsong/ASRepository/ASRepository/RepsotioryAssembly.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Humming/HummingView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Humming/HummingViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Rehumming/RehummingView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Rehumming/RehummingViewModel.swift
Labels: feat

#126 feat: 제출 시 로딩UI 띄우기, 제출 버튼 비활성화
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ASAlertController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ASButton.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Game/GameNavigationController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Humming/HummingView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Humming/HummingViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Rehumming/RehummingView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Rehumming/RehummingViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SelectMusic/SelectMusicViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SelectMusic/SelectMusicViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SubmitAnswer/SubmitAnswerViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SubmitAnswer/SubmitAnswerViewModel.swift
Labels: feat

#130 feat: Status 에따른 화면 전환 로직, 에러 처리 부분 완성
  alsongDalsong/ASEntity/ASEntity/GameState.swift
  alsongDalsong/ASEntity/ASEntity/Music.swift
  alsongDalsong/ASMusicKit/ASMusicKit/ASMusicAPI.swift
  alsongDalsong/ASMusicKit/ASMusicKit/CGColor+Hex.swift
  alsongDalsong/ASNetworkKit/ASNetworkKit/ASNetworkErrors.swift
  alsongDalsong/ASRepository/ASRepository/Protocols/RepositoryProtocols.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/GameStateRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/MainRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/MusicRepository.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ASAlertController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ProgressBar.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Extensions/Color+Hex.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Game/GameNavigationController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Humming/HummingView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Humming/HummingViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Lobby/LobbyViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Lobby/LobbyViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/MusicPanel/MusicPanelViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Onboarding/OnboardingViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Onboarding/OnboardingViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Rehumming/RehummingView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Rehumming/RehummingViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SelectMusic/ASMusicItemCell.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SelectMusic/SelectMusicView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SelectMusic/SelectMusicViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SelectMusic/SelectMusicViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SubmitAnswer/SelectAnswerView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SubmitAnswer/SubmitAnswerViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SubmitAnswer/SubmitAnswerViewModel.swift
  firebase/functions/api/ResetGame.js
  firebase/functions/api/SubmitAnswer.js
  firebase/functions/api/SubmitMusic.js
  firebase/functions/api/UploadRecord.js
  firebase/functions/index.js
Labels: feat

#129 feat: 허밍, 리허밍 뷰 제출 완료 상태 추가
  alsongDalsong/ASAudioKit/ASAudioKit/ASAudioRecorder/ASAudioRecorder.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ASButton.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Extensions/String+.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Utils/AudioHelper.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Humming/HummingView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Humming/HummingViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Lobby/LobbyViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/MusicPanel/MusicPanel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/MusicPanel/MusicPanelViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/RecordingPanel/AudioButtonState.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/RecordingPanel/RecordingPanel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/RecordingPanel/RecordingPanelViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Rehumming/RehummingView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Rehumming/RehummingViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Result/HummingResultViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SelectMusic/SelectMusicViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SelectMusic/SelectMusicViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SubmitAnswer/SubmitAnswerViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SubmitAnswer/SubmitAnswerViewModel.swift
Labels: feat

#138 feat: 음악 선택 뷰 + 제출 현황
  alsongDalsong/ASRepository/ASRepository/Protocols/RepositoryProtocols.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/AnswersRepository.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Game/GameNavigationController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Humming/HummingView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Humming/HummingViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Rehumming/RehummingView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Rehumming/RehummingViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SelectMusic/SelectMusicView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SelectMusic/SelectMusicViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SelectMusic/SelectMusicViewModel.swift
Labels: feat

#142 fix: 제출 현황 제대로 안 보이는 문제 해결
  alsongDalsong/ASRepository/ASRepository/Protocols/RepositoryProtocols.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/RecordsRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/SubmitsRepository.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Humming/HummingViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Rehumming/RehummingViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SubmitAnswer/SubmitAnswerViewModel.swift
Labels: fix

#146 feat: 로비 뷰 일부 수정
  alsongDalsong/ASEntity/ASEntity/Mode.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Resources/Assets.xcassets/ModeImage/Contents.json
  alsongDalsong/alsongDalsong/alsongDalsong/Resources/Assets.xcassets/ModeImage/harmony.imageset/Contents.json
  alsongDalsong/alsongDalsong/alsongDalsong/Resources/Assets.xcassets/ModeImage/harmony.imageset/harmony.png
  alsongDalsong/alsongDalsong/alsongDalsong/Resources/Assets.xcassets/ModeImage/humming.imageset/Contents.json
  alsongDalsong/alsongDalsong/alsongDalsong/Resources/Assets.xcassets/ModeImage/humming.imageset/humming.png
  alsongDalsong/alsongDalsong/alsongDalsong/Resources/Assets.xcassets/ModeImage/instant.imageset/Contents.json
  alsongDalsong/alsongDalsong/alsongDalsong/Resources/Assets.xcassets/ModeImage/instant.imageset/instant.png
  alsongDalsong/alsongDalsong/alsongDalsong/Resources/Assets.xcassets/ModeImage/sync.imageset/Contents.json
  alsongDalsong/alsongDalsong/alsongDalsong/Resources/Assets.xcassets/ModeImage/sync.imageset/sync.png
  alsongDalsong/alsongDalsong/alsongDalsong/Resources/Assets.xcassets/ModeImage/tts.imageset/Contents.json
  alsongDalsong/alsongDalsong/alsongDalsong/Resources/Assets.xcassets/ModeImage/tts.imageset/tts.png
  alsongDalsong/alsongDalsong/alsongDalsong/Resources/Assets.xcassets/fake.imageset/fake@2x.png
  alsongDalsong/alsongDalsong/alsongDalsong/Resources/Assets.xcassets/fake.imageset/fake@3x.png
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/SwiftUIComponents/ModeView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/SwiftUIComponents/ProfileView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ASAlertController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ASButton.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Lobby/LobbyView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Lobby/LobbyViewController.swift
Labels: feat

#144 feat: 재녹음 시 파형을 다시 그릴 수 있도록 변경
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/RecordingPanel/RecordingPanel.swift
Labels: feat

#150 fix: 동시 제출 화면 전환이 안되는 이슈 해결
  alsongDalsong/ASNetworkKit/ASNetworkKit/FirebaseEndpoint.swift
  firebase/functions/api/SubmitAnswerV2.js
  firebase/functions/api/SubmitMusicV2.js
  firebase/functions/api/UploadRecordV2.js
  firebase/functions/index.js
Labels: fix, QA, bug
