Repository boostcampwm-2024/iOS07-alsongDalsong, pull requests merged in 2024-12, with the labels that each got.

#157 fix 아바타 수정
  alsongDalsong/ASRepository/ASRepository/Repositories/AvatarRepository.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ASRefreshButton.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ProgressBar.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Lobby/LobbyView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Rehumming/RehummingView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Rehumming/RehummingViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Result/HummingResultViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Result/HummingResultViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SelectMusic/SelectMusicViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SelectMusic/SelectMusicViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SubmitAnswer/SubmitAnswerViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SubmitAnswer/SubmitAnswerViewModel.swift
  firebase/functions/api/JoinRoom.js
Labels: fix, QA

#160 feat: 결과화면에서 로비로 이동, 결과화면 로딩 Alert 추가
  alsongDalsong/ASNetworkKit/ASNetworkKit/FirebaseEndpoint.swift
  alsongDalsong/ASRepository/ASRepository/Protocols/MainRepositoryProtocol.swift
  alsongDalsong/ASRepository/ASRepository/Protocols/RepositoryProtocols.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/MainRepository.swift
  alsongDalsong/ASRepository/ASRepository/Repositories/RoomActionRepository.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ASAlertController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ASButton.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Result/HummingResultViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Result/HummingResultViewModel.swift
  firebase/functions/api/ResetGame.js
Labels: feat

#166 refactor: Alert controller, ASButton 리팩토링 및 간단한 디자인 수정
  alsongDalsong/alsongDalsong/alsongDalsong/Resources/Assets.xcassets/asLightRed.colorset/Contents.json
  alsongDalsong/alsongDalsong/alsongDalsong/Resources/Assets.xcassets/asLightSky.colorset/Contents.json
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ASAlertController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ASButton.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/Alert/ASAlertController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/Alert/DefaultAlertController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/Alert/InputAlertController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/Alert/LoadingAlertController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/Alert/SingleButtonAlertController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Extensions/UIViewController+present.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Humming/HummingView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Lobby/LobbyViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Onboarding/OnboardingViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Rehumming/RehummingView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Result/HummingResultViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SelectMusic/SelectMusicViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SubmitAnswer/SubmitAnswerViewController.swift
Labels: refactor

#163 feat: 재생 시 파형 색상 변경
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/AudioVisualizerView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Utils/AudioHelper.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/RecordingPanel/RecordingPanel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/RecordingPanel/RecordingPanelViewModel.swift
Labels: feat

#169 feat: NavigationBar에 나가기 버튼, 타이틀 라운드별로 적용
  alsongDalsong/ASEntity/ASEntity/GameState.swift
  alsongDalsong/ASRepository/ASRepository/Protocols/RepositoryProtocols.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/SceneDelegate.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Game/GameNavigationController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Lobby/LobbyViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Onboarding/OnboardingViewController.swift
Labels: feat

#170 feat: 정답 제출 뷰에 선택한 정답 표시
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Utils/AudioHelper.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/MusicPanel/ASMusicPlayerView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/MusicPanel/MusicPanel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/MusicPanel/MusicPanelViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/RecordingPanel/RecordingPanelViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SubmitAnswer/SubmitAnswerViewController.swift
Labels: feat

#172 feat: Guide ViewController 제작
  alsongDalsong/ASEntity/ASEntity/GameState.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/Alert/ASAlertController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/CornerImageView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/GuideLabel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Extensions/UIColor+Hex.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Game/GameNavigationController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Guide/GuideViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Humming/HummingView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Rehumming/RehummingView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Result/HummingResultViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Result/HummingResultViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SubmitAnswer/SubmitAnswerViewController.swift
Labels: feat

#159 feat: 방장이 모드 선택중 추가 (시작하기 버튼 로직 수정)
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Components/UIKitComponents/ASButton.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Lobby/LobbyViewController.swift
Labels: feat

#162 fix: 결과 화면 UI 및 기능 관련 수정 사항 개선
  alsongDalsong/alsongDalsong/alsongDalsong/Localizable.xcstrings
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Utils/AudioHelper.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/RecordingPanel/RecordingPanelViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Result/HummingResultViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Result/HummingResultViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SelectMusic/SelectMusicView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SelectMusic/SelectMusicViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SubmitAnswer/SelectAnswerView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SubmitAnswer/SubmitAnswerViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SubmitAnswer/SubmitAnswerViewModel.swift
Labels: fix

#180 feat: 음악 선택 화면에서 시간 다 될 때까지 아무 음악도 고르지 않으면 랜덤한 음악 제출
  alsongDalsong/ASMusicKit/ASMusicKit/ASMusicAPI.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SelectMusic/SelectMusicViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SelectMusic/SelectMusicViewModel.swift
Labels: feat

#181 bugfix: 키보드 동작 오류 수정
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Extensions/UIViewController+Keyboard.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/Onboarding/OnboardingViewController.swift
Labels: fix

#179 fix: 노래 검색, 정답 제출 1차QA
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SelectMusic/SelectMusicView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SelectMusic/SelectMusicViewModel.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SubmitAnswer/SelectAnswerView.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SubmitAnswer/SubmitAnswerViewController.swift
  alsongDalsong/alsongDalsong/alsongDalsong/Sources/Views/SubmitAnswer/SubmitAnswerViewModel.swift
Labels: fix, QA

#183 docs: readme 업데이트
  README.md
Labels: documentation
